_core:
  default_config_hash: HlN7eAN2N4JIHsYv56V4E7sqC9bS609KwvGFjyD_mgk
langcode: en
uuid: ccb5609b-682c-4e93-b796-21f1c5ea7308
name: 'The GOAT Drupal CMS Site'
mail: admin@example.com
slogan: ''
page:
  403: /user/login
  404: ''
  front: /node/2
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: null
